/*
 * Project name:
     tft_test.vtft
 * Generated by:
     Visual TFT
 * Date of creation
     4/25/2022
 * Test configuration:
     MCU:             STM32F107VC
     Dev.Board:       new_pattern_name
     Oscillator:      72000000 Hz
     SW:              mikroC PRO for ARM
 */

#include "tft_test_objects.h"

void main() {

  InitVTFTStack();

  while (1) {
    ProcessVTFTStack();
  }

}