/*
 * Project name:
     tft_test.mcpar
 * Generated by:
     Visual TFT
 * Date of creation
     4/25/2022
 * Test configuration:
     MCU:             STM32F107VC
     Dev.Board:       EasyMx_PRO_v7_for_STM32_ARM
                      http://www.mikroe.com/easymx-pro/stm32/
     Oscillator:      72000000 Hz
     SW:              mikroC PRO for ARM
                      http://www.mikroe.com/mikroc/arm/
 */

#include "tft_test_objects.h"

void main() {

  Start_TP();

  while (1) {
    Check_TP();
  }
}