/*
 * Project name:
     Snake2022.mcpar
 * Generated by:
     Visual TFT
 * Date of creation
     4/28/2022
 * Test configuration:
     MCU:             STM32F107VC
     Dev.Board:       EasyMx_PRO_v7_for_STM32_ARM_9A
     Oscillator:      72000000 Hz
     SW:              mikroC PRO for ARM
                      http://www.mikroe.com/mikroc/arm/
 */

#include "Snake2022_main.h"

void PlayScreen(){
  // Initialize Play Screen
  TFT_Write_Text("Snake Game made by Frank Pellicano, 2022",30,220);
  TFT_Write_Text("Score = ",225,0);
  TFT_Write_Char(scoreD1+48,280,0);
  TFT_Write_Char(scoreD2+48,290,0);
  TFT_Write_Char(scoreD3+48,300,0);

  // Initialize apple
  apple.x1 = 20;
  apple.y1 = 20;
  apple.x2 = 20;
  apple.y2 = 20;
  apple.color = CL_RED;

  // Initialize Snake
  snake[0].x1 = 100;
  snake[0].y1 = 100;
  snake[0].x2 = 120;
  snake[0].y2 = 120;
  snake[0].color = CL_GREEN;
  TFT_Set_Brush(1,snake[0].color,0,0,0,0);
  TFT_Rectangle(snake[0].x1,snake[0].y1,snake[0].x2,snake[0].y2);

 snakeDir = 3;

  srand(getAdcReading());
  death = 0;
  RandomizeApple();

  PlaySong();
  tsec = 0;
  tmin = 0;
  while(death == 0){
      if(timerFlag == 1){  // RTC
        timerFlag = 0;
        TFT_Set_Font(TFT_defaultFont, CL_SILVER, FO_HORIZONTAL);
        TFT_Write_Char(((tmin-tmin%100)/100)+48,50,0);
        TFT_Write_Char(((tmin%100 - tmin%10)/10)+48,60,0);
        TFT_Write_Char((tmin%10)+48,70,0);
        TFT_Write_Char(':',80,0);
        TFT_Write_Char(((tsec-tsec%10)/10)+48,90,0);
        TFT_Write_Char((tsec%10)+48,100,0);
        tsec++;
        if(tsec == 60){
          tmin++;
          tsec = 0;
        }
        TFT_Set_Font(TFT_defaultFont, CL_GREEN, FO_HORIZONTAL);
        TFT_Write_Char(((tmin-tmin%100)/100)+48,50,0);
        TFT_Write_Char(((tmin%100 - tmin%10)/10)+48,60,0);
        TFT_Write_Char((tmin%10)+48,70,0);
        TFT_Write_Char(':',80,0);
        TFT_Write_Char(((tsec-tsec%10)/10)+48,90,0);
        TFT_Write_Char((tsec%10)+48,100,0);
      }


    // Draw head
    TFT_Set_Brush(1,snake[0].color,0,0,0,0);
    TFT_Rectangle(snake[0].x1,snake[0].y1,snake[0].x2,snake[0].y2);

    for(i = 0; i < gameSpeed; i++){
      gameSpeed = getAdcReading()/9 + 100; // Force update speed between 100-500ms
      delay_ms(1);
    }

    // Remove tail
    TFT_Set_Brush(1,CL_BLACK,0,0,0,0);
    TFT_Rectangle(snake[nodes].x1,snake[nodes].y1,snake[nodes].x2,snake[nodes].y2);


    if(snake[0].x1 == apple.x1 & snake[0].y1 == apple.y1){  // Apple Collision
      score++;
      nodes++;
      snake[nodes].color = CL_GREEN;

      TFT_Set_Pen(CL_SILVER, 1);
      TFT_Set_Brush(1,CL_SILVER,0,0,CL_SILVER,CL_SILVER);
      TFT_Rectangle(280,0,340,19);
      TFT_Set_Pen(CL_BLACK, 1);
      scoreD3 = score%10;
      scoreD2 = (score%100 - scoreD3 ) / 10;
      scoreD1 = (score - score%100)/ 100;
      TFT_Write_Char(scoreD1+48,280,0);
      TFT_Write_Char(scoreD2+48,290,0);
      TFT_Write_Char(scoreD3+48,300,0);

      RandomizeApple();

      if(soundEnabled == 1){
        Sound_Play(500, 10);
      }
    }
    for(i = 1; i <= nodes; i++){ // Self Collision Check
      if(snake[0].x1 == snake[i].x1 & snake[0].y1 == snake[i].y1){ // Self Collision Detected
        death = 1;
      }
    }
    // Shift Coordinates
    for(i = nodes; i >= 1; i--){
      snake[i].x1 = snake[i-1].x1;
      snake[i].y1 = snake[i-1].y1;
      snake[i].x2 = snake[i-1].x2;
      snake[i].y2 = snake[i-1].y2;
    }

    // Joystick Handler
    switch(snakeDir){
    case 0:    // LEFT
      GPIOD_ODR = 0;
      GPIOD_ODR.B14 = 1;
      if(snake[0].x1 > 20){
          snake[0].x1 -= 20;
          snake[0].x2 -= 20;

   }  else {
      death = 1;
   }
      break;
    case 1: // UP
      GPIOD_ODR = 0;
      GPIOD_ODR.B11 = 1;
      if(snake[0].y1 > 20){

        snake[0].y1 -= 20;
        snake[0].y2 -= 20;
   }  else {
      death = 1;
   }
      break;
    case 2:     // DOWN
      GPIOD_ODR = 0;
      GPIOD_ODR.B9 = 1;
      if(snake[0].y1 < 200){

        snake[0].y1 += 20;
        snake[0].y2 += 20;
   }  else {
      death = 1;
   }
      break;
    case 3:   // Right
      GPIOD_ODR = 0;
      GPIOD_ODR.B6 = 1;
      if(snake[0].x1 < 280){

        snake[0].x1 += 20;
        snake[0].x2 += 20;
   }  else {
      death = 1;
   }
      break;
    default:
      break;
    }

    if(death){
      break;
    }
  }
}

void main() {
  // Initialize Hardware
  InitializeUSART1();		// Call sub function to initialize USART1
  AdcConfiguration();
  JoyStickConfiguration();
  Timer3IntConfiguration();
  Start_TP();
  
  Sound_Init(&GPIOE_ODR, 14);
  TFT_Set_Font(TFT_defaultFont, CL_GREEN, FO_HORIZONTAL);

  for(;;){
    ClearScreen();
    stateMachine = TitleScreen();
    ClearScreen();

    if(stateMachine == 80){ // Play Game
        PlayScreen();
        GameOverScreen();
    }
    if(stateMachine == 100){ // Load high scores screen
        ScoreScreen();
    }
    if(stateMachine == 120){ // How To Play
       HowToScreen();
    }
  }
}

void RandomizeApple(){
  appleMatch = 1; // Assume the apple will randomly match with the snake
  matchCount = 0;
  
  while(appleMatch == 1 & matchCount < 192){  // Randomize until apple is not appearing on snake
    apple.x1 = rand()/118;
    apple.x1 += SNAKESIZE-(apple.x1 % SNAKESIZE);
    apple.y1 = rand()/165;
    apple.y1 += SNAKESIZE-(apple.y1 % SNAKESIZE);

    for(i = 0; i <= nodes; i++){  // Check for match with all snake nodes
        if(apple.x1 == snake[i].x1 || apple.y1 == snake[i].y1){
          appleMatch = 1;// Match, redraw apple
          matchCount++;
          break;
        } else {
          appleMatch = 0;
        }
    }
  }
  
   // Draw the new apple
  apple.x2 = apple.x1 + SNAKESIZE;
  apple.y2 = apple.y1 + SNAKESIZE;
  TFT_Set_Brush(1,apple.color,0,0,0,0);
  TFT_Rectangle(apple.x1,apple.y1,apple.x2,apple.y2);
}


void ClearScreen(){
  TFT_Set_Pen(CL_SILVER, 1);
  TFT_Set_Brush(1,CL_SILVER,0,0,0,0);
  TFT_Rectangle(0,0,320,240);
  TFT_Set_Pen(CL_BLACK, 1);
  TFT_Set_Brush(1,CL_BLACK,0,0,0,0);
  TFT_Rectangle(20,20,300,220);
  TFT_Set_Font(TFT_defaultFont, CL_GREEN, FO_HORIZONTAL);
  TFT_Write_Text("Snake Game made by Frank Pellicano, 2022",30,220);
}

void PlaySong(){
  Sound_Play(NOTE_F5, 240);
  Sound_Play(NOTE_Bf5, 240);
  Sound_Play(NOTE_G5, 240);
  Sound_Play(NOTE_C6, 240);
  Sound_Play(NOTE_F5, 240);
  Sound_Play(NOTE_Bf5, 240);
  Sound_Play(NOTE_G5, 240);
  Sound_Play(NOTE_C6, 240);
  Sound_Play(NOTE_A5, 160);
  Sound_Play(NOTE_Bf5, 160);
  Sound_Play(NOTE_G5, 160);
  Sound_Play(NOTE_F5, 160);
  Sound_Play(NOTE_Bf5, 160);
  Sound_Play(NOTE_A5, 160);
  Sound_Play(NOTE_G5, 160);
  Sound_Play(NOTE_D5, 160);
  Sound_Play(NOTE_G5, 160);
  Sound_Play(NOTE_D5, 160);
  Sound_Play(NOTE_C5, 160);
  Sound_Play(NOTE_E5, 160);
  Sound_Play(NOTE_F5, 1000);
}
