/*
 * Project name:
     tft_test2.mcpar
 * Generated by:
     Visual TFT
 * Date of creation
     4/25/2022
 * Test configuration:
     MCU:             STM32F107VC
     Dev.Board:       EasyMx_PRO_v7_for_STM32_ARM_9A
     Oscillator:      72000000 Hz
     SW:              mikroC PRO for ARM
                      http://www.mikroe.com/mikroc/arm/
 */

#include "tft_test2_objects.h"

void main() {
  unsigned int counter = 0;
  Start_TP();
  RCC_APB2ENR |= 1 << 2;
  GPIOA_CRL = 0x44444444;

         TFT_Set_Brush(1, CL_BLACK, 0, 0, 0, 0);
        TFT_Rectangle(0,0,320, 240);

// Enable gradient from black to white color, left-right orientation
  while (1) {
       
        TFT_Set_Brush(1, CL_AQUA, 0, 0, 0, 0);
        TFT_Rectangle(counter+50,0,counter+100, 50);
        

        if (GPIOA_IDR.B0 == 1) {
            if (counter < 240-50) {
                TFT_Set_Brush(1, CL_BLACK, 0, 0, 0, 0);
                TFT_Rectangle(counter+50,0,counter+100, 50);
            }


            counter+=25;

        }
        Delay_ms(10);
        

        //if (counter >= 320) {
        //    counter -=25;
        //}

    Check_TP();
  }
}